const data={
    products: [
        {
          name: 'Logitic Keyboard',
          slug: 'logitic-keyboard',
          category: 'Keyboard',
          image: "/images/318ofRk1jyL.jpg",
          price: 90,
          brand: 'Logitic',
          rating: 4.0,
          numReviews: 8,
          countInStock: 20,
          description: 'Affordable and quiet',
        },
        {
          name: 'Razer Mini-analog',
          slug: 'razer-mini-analog',
          category: 'keyboard',
          image: '/images/razer-cynosa-v2-500x500.png',
          price: 120,
          brand: 'Razer',
          rating: 3.2,
          numReviews: 10,
          countInStock: 10,
          description: 'Mini keyboard suit for girls',
        },
        {
          name: 'Razer-blackwidow-v3',
          slug: 'razer-blackwidow-v3',
          category: 'keyboard',
          image: '/images/razer-blackwidow-v3-category-500x500.jpg',
          price: 190,
          brand: 'Razer',
          rating: 4.5,
          numReviews: 5,
          countInStock: 20,
          description: 'Black suit for guy',
        },
        {
          name: 'Deathstalker-v2',
          slug: 'deathstalker-v2',
          category: 'keyboard',
          image: '/images/razer-ornata-v3-base.png',
          price: 130,
          brand: 'Razer',
          rating: 2.9,
          numReviews: 13,
          countInStock: 20,
          description: 'White keyboard',
        },
        {
          name: 'Huntsman-v2',
          slug: 'huntsman-v2-',
          category: 'Keyboard',
          image: '/images/huntsman-v2-tkl-1500x1000-1.jpg',
          price: 195,
          brand: 'Razer',
          rating: 3.5,
          numReviews: 7,
          countInStock: 20,
          description: 'sharp looking keyboard',
        },
        {
          name: 'Ynosa-V2-Phoenix-Hero',
          slug: 'ynosa-V2-Phoenix-Hero',
          category: 'keyboard',
          image: '/images/ynosa-V2-Phoenix-Hero_1500x1000.jpg',
          price: 175,
          brand: 'Razer',
          rating: 2.4,
          numReviews: 14,
          countInStock: 20,
          description: 'Quiet, cushioned keystrokes',
        },
        {
          
          name: 'Huntsman-te-se-gallery-',
          slug: 'huntsman-te-se-gallery-',
          category: 'keyboard',
          image: '/images/huntsman-te-se-gallery-150x1000-2.jpg',
          price: 160,
          brand: 'Razer',
          rating: 3.0,
          numReviews: 20,
          countInStock: 30,
          description: 'Razer Linear Optical Switches for faster',
        },
        {
          
          name: 'Razer Huntsman Mini Analog ',
          slug: 'razer-huntsman-mini-analog',
          category: 'keyboard',
          image: '/images/-1500x1000-4.jpg',
          price: 150,
          brand: 'Razer',
          rating: 3.0,
          numReviews: 20,
          countInStock: 30,
          description: '60% Gaming Keyboard with Analog Optical Switches',
        },
        {
 
          name: 'RAZER VIPER MINI',
          slug: 'razer-viper-mini',
          category: 'mouse',
          image: '/images/Untitled-1-330x409.jpg',
          price: 29,
          brand: 'Razer',
          rating: 3.0,
          numReviews: 20,
          countInStock: 10,
          description: 'GAMING MOUSE',
  
        },
        {
   
          name: 'LOGITECH G502 HERO ',
          slug: 'loitic-g502-hero',
          category: 'mouse',
          image: '/images/5402-4-330x409.jpg',
          price: 79,
          brand: 'Logitic',
          rating: 3.0,
          numReviews: 20,
          countInStock: 10,
          description: 'HIGH PERFORMANCE GAMING MOUSE',
  
        },
        {
   
          name: 'LOGITECH G102 LIGHTSYNC',
          slug: 'logitic-g102-lightsync-white',
          category: 'mouse',
          image: '/images/white-4-330x409.jpg',
          price: 21,
          brand: 'Logitic',
          rating: 2.0,
          numReviews: 50,
          countInStock: 5,
          description: 'GAMING MOUSE',
  
        },
        {
   
          name: 'ASUS P504 ROG GLADIUS II',
          slug: 'asus-P504-rog-gladius-II',
          category: 'mouse',
          image: '/images/ASUS P504-330x409.jpg',
          price: 70,
          brand: 'Asus',
          rating: 4.0,
          numReviews: 10,
          countInStock: 5,
          description: 'GAMING MOUSE',
  
        },
        {
   
          name: 'RAZER LANCEHEAD ',
          slug: 'razer-lancehead-tournament-edition',
          category: 'mouse',
          image: '/images/tournament edition-1-330x409.jpg',
          price: 59,
          brand: 'Razer',
          rating: 5.0,
          numReviews: 15,
          countInStock: 12,
          description: 'GAMING MOUSE( 16,000DPI,RGB) TOURNAMENT EDITION',
  
        },
      
      ],
      // mouse

    };
    
    export default data;
